/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.nsu.ccfit.gerasimov2.a.game;

import ru.nsu.ccfit.gerasimov2.a.game.controller.Controller;
import ru.nsu.ccfit.gerasimov2.a.game.controller.DefaultController;
import ru.nsu.ccfit.gerasimov2.a.game.model.Match3Model;
import ru.nsu.ccfit.gerasimov2.a.game.model.GameModel;
import ru.nsu.ccfit.gerasimov2.a.game.view.ConsoleView;
import ru.nsu.ccfit.gerasimov2.a.game.view.View;
import ru.nsu.ccfit.gerasimov2.a.game.view.swing.SwingView;

public class App {

    private static void startGame(boolean isConsoleMode) {
        GameModel model = new Match3Model(10, 10, 5);
        View view = isConsoleMode ? new ConsoleView(model) : new SwingView(model);
        Controller controller = new DefaultController(model, view);
        view.setController(controller);
        view.start();
    }
    public static void main(String[] args) {
        boolean isConsoleMode = true;
        startGame(isConsoleMode);
    }
        
}
