/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.nsu.ccfit.gerasimov2.a;

import ru.nsu.ccfit.gerasimov2.a.factory.storage.MotorStorage;
import ru.nsu.ccfit.gerasimov2.a.factory.storage.Storage;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        MotorStorage storage = new MotorStorage();
    }
}
