LogSale=0
LogFileName=sales.log

NumDealers=8
NumAccessorySuppliers=2
NumWorkers=8

CarStorageSize=1500
AccessoryStorageSize=2000
MotorStorageSize=3000
BodyStorageSize=2500

CriticalCarStorageSize=100
NumRequests=500