LogSale=0
LogFileName=sales.log

NumDealers=4
NumAccessorySuppliers=2
NumWorkers=15

CarStorageSize=150
AccessoryStorageSize=200
MotorStorageSize=300
BodyStorageSize=250

CriticalCarStorageSize=10
NumRequests=40